yaml

name: Scrape K-Five and Update Data

on:
  schedule:
    - cron: "0 6 * * *"  # 03:00 Buenos Aires (UTC-3) = 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: scraper
        run: npm ci

      - name: Run scraper
        working-directory: scraper
        env:
          MARKUP_PCT: "50"
        run: npm start

      - name: Commit changes (if any)
        run: |
          git config user.name "chacal-bot"
          git config user.email "actions@github.com"
          git add data/products.json data/kfive_captura_con_50.csv
          if git diff --cached --quiet; then
            echo "No hay cambios para commitear."
          else
            git commit -m "chore: update data from K-Five [skip ci]"
            git push
          fi
